### ISSUE TITLE
KiCad Version Issue

### ISSUE THREAD

**Issue by qwertymodo** [rattboi/extron-scart-adapter#7]
It seems like the KiCad files were created using a nightly build from 5/16/2019.  This causes issues trying to open the files using the stable release versions, as even versions that are newer than 5/16/2019, such as the current v5.1.4, released 8/4/2019, complain that they can't open the files because they were created with a more recent version than the one you're running.  This seems like a bug in KiCad, but I figured it was worth reporting here as well.

**Comment by rattboi** [comment]
Sorry about that!

Fixed with https://github.com/rattboi/extron-scart-adapter/pull/8
